name: Bump version and publish to NPM

on:
  workflow_dispatch:
    inputs:

      is-main-release:
        required: true
        type: boolean
        description: Publish with the "latest" tag (NPM)
        default: false

      tag-from-branch:
        required: true
        type: boolean
        description: '-prerelease suffix from branch name, rather than "-beta". Ignored for "latest" tag'
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Bump version
        run: |
          echo npm version ${{ github.event.inputs.is-main-release && 'patch' || 'prerelease' }} ${{ !github.event.inputs.is-main-release && (--preid=github.event.inputs.tag-from-branch && 'beta' || $(echo ${GITHUB_REF#refs/heads/})) }}
      #- run: npm publish --tag=${{ github.event.inputs.npm-tag }}

      #- run: npm run test
      #- run: npm version ${{ github.event.inputs.message }}
      #- run: npm run build
      #- run: npm publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
