name: Bump version and publish to NPM

on:
  workflow_dispatch:
    inputs:

      is-main-release:
        required: true
        type: boolean
        description: 'Release with the "latest" tag (NPM)'
        default: 'false'

      tag-from-branch:
        required: true
        type: boolean
        description: 'Prerelease with -<branch-name> suffix'
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Configure Git user
        run: |
          git config --global user.email "drill4j-release-bot@gmail.com"
          git config --global user.name "drill4j-release-bot"
      - name: Main release, "latest" tag
        if: github.event.inputs.is-main-release == 'true'
        run: |
          npm version patch
      - name: Prerelease, "beta" tag, "-beta" suffix)
        if: github.event.inputs.is-main-release != 'true' && github.event.inputs.tag-from-branch != 'true'
        run: |
          npm version prerelease --preid=beta
      - name: Prerelease, "beta" tag, "-<branch-name>" suffix)
        if: github.event.inputs.is-main-release != 'true' && github.event.inputs.tag-from-branch == 'true'
        run: |
          if [ $GITHUB_REF = refs/heads/main ]; \
          then echo 'NOOOO!'; echo 'Do not use -<branch-name> to release from "main" branch'; exit 1; \
          else echo 'RELEEEEASE!'; str=${GITHUB_REF#refs/heads/}; echo ${str//'/'/'-'}; npm version prerelease --preid=$str; \
          fi;
        #  if [ $GITHUB_REF = refs/heads/main ]; \
        #  then \
        #  npm version prerelease --preid=$(str=${GITHUB_REF#refs/heads/}; echo ${str//'/'/'-'}); fi;
        # else npm version prerelease --preid=$(echo ${GITHUB_REF#refs/heads/}); fi;

      - name: Push commit with new tag
        run: |
          git push origin $(echo ${GITHUB_REF#refs/heads/})
