name: Bump version and publish to NPM

on:
  workflow_dispatch:
    inputs:

      is-main-release:
        required: true
        type: boolean
        description: Publish with the "latest" tag (NPM)
        default: 'false'

      tag-from-branch:
        required: true
        type: boolean
        description: '-prerelease suffix from branch name, rather than "-beta". Ignored for "latest" tag'
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      #- run: echo is main release *${{github.event.inputs.is-main-release == 'true'}}*
      #- run: echo tag from branch *${{github.event.inputs.tag-from-branch == 'true'}}*
      #- run: echo ${{ (github.event.inputs.is-main-release != 'true' && github.event.inputs.tag-from-branch != 'true') && 'beta' || 'no beta' }}
      #- run: echo ${{ (github.event.inputs.is-main-release != 'true' && github.event.inputs.tag-from-branch == 'true' ) && 'branchname' || 'no branchname' }}

      - name: Configure Git user
        run: |
          git config --global user.email "foo@bar.fiz"
          git config --global user.name "Foo Bar"

      - name: Main release, "latest" tag
        if: github.event.inputs.is-main-release == 'true'
        run: |
          npm version patch

      - name: Prerelease, "beta" tag, "-beta" suffix)
        if: github.event.inputs.is-main-release != 'true' && github.event.inputs.tag-from-branch != 'true'
        run: |
          npm version prerelease --preid=beta

      - name: Prerelease, "beta" tag, "-<branch-name>" suffix)
        if: github.event.inputs.is-main-release != 'true' && github.event.inputs.tag-from-branch == 'true'
        run: |
          echo $GITHUB_REF
        #refs/heads/ = "main"
        #  if [ $? -eq 0 ]; then echo 1; else echo 0; fi
        #  GITHUB_REF#refs/heads/ == 'main'
        # && echo #${{ ${GITHUB_REF#refs/heads/} == 'main' }}#
        # && $(echo 'You are trying to publish prerelease with -<branch-name> suffix from the "main" branch' && exit 1) }} \
        #    npm version prerelease --preid=$(echo ${GITHUB_REF#refs/heads/})

      #- name: Push git tag
      #  run: |
      #    git push origin $(echo ${GITHUB_REF#refs/heads/})
      #    git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" "${{ github.head_ref }}"
          
      #- run: npm publish --tag=${{ github.event.inputs.npm-tag }}

      #- run: npm run test
      #- run: npm version ${{ github.event.inputs.message }}
      #- run: npm run build
      #- run: npm publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
