name: Use package.json version
on:
  # just for EXAMPLE
  workflow_dispatch:
  # just for EXAMPLE

jobs:
  do-something:
    name: Do something
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version from package.json
        id: get_version
        shell: bash
        
        run: |
          echo ::set-output name=tag::$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)

      - name: Use version
        run: echo Version is ${{steps.get_version.outputs.tag}}!
